<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bahan_olahan_model extends CI_Model
{

    public $table = 'bahan_olahan';
    public $id = 'bahan_olahan_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('bahan_olahan_id,nama_bahan,satuan,stok');
        $this->datatables->from('bahan_olahan');
        //add this line for join
        //$this->datatables->join('table2', 'bahan_olahan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('bahan_olahan/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('bahan_olahan/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('bahan_olahan/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'bahan_olahan_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('bahan_olahan_id', $q);
	$this->db->or_like('nama_bahan', $q);
	$this->db->or_like('satuan', $q);
	$this->db->or_like('stok', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('bahan_olahan_id', $q);
	$this->db->or_like('nama_bahan', $q);
	$this->db->or_like('satuan', $q);
	$this->db->or_like('stok', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Bahan_olahan_model.php */
/* Location: ./application/models/Bahan_olahan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-15 22:56:28 */
/* http://harviacode.com */