<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Investasi_generalmanager_model extends CI_Model
{

    public $table = 'investasi';
    public $id = 'investasi_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('b.full_name as nama_bendahara,g.full_name as nama_generalmanager,investasi_id,nama_investasi,nominal,tanggal,jumlah,masa_pemanfaatan,status,id_users_bendahara,id_users_generalmaanager');
        $this->datatables->from('investasi');
       // $this->datatables->join('tbl_user_level', 'tbl_user_level.id_user_level = tbl_user.id_user_level');
        //add this line for join
        $this->datatables->join('tbl_user b', 'b.id_users = investasi.id_users_bendahara');
        $this->datatables->join('tbl_user g', 'g.id_users = investasi.id_users_generalmaanager');
       
        $this->datatables->add_column('action', anchor(site_url('investasi/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('investasi/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 

                ".anchor(site_url('investasi/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'investasi_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('investasi_id', $q);
	$this->db->or_like('nama_investasi', $q);
	$this->db->or_like('nominal', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('id_users_bendahara', $q);
	$this->db->or_like('id_users_generalmaanager', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('investasi_id', $q);
	$this->db->or_like('nama_investasi', $q);
	$this->db->or_like('nominal', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('id_users_bendahara', $q);
	$this->db->or_like('id_users_generalmaanager', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Investasi_model.php */
/* Location: ./application/models/Investasi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-01 07:28:59 */
/* http://harviacode.com */