<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Investor_model extends CI_Model
{

    public $table = 'investor';
    public $id = 'investor_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('investor_id,nama_investor,alamat_investor,telp_investor,id_users_owner');
        $this->datatables->from('investor');
        //add this line for join
        //$this->datatables->join('table2', 'investor.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('investor/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('investor/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('investor/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'investor_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('investor_id', $q);
	$this->db->or_like('nama_investor', $q);
	$this->db->or_like('alamat_investor', $q);
	$this->db->or_like('telp_investor', $q);
	$this->db->or_like('id_users_owner', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('investor_id', $q);
	$this->db->or_like('nama_investor', $q);
	$this->db->or_like('alamat_investor', $q);
	$this->db->or_like('telp_investor', $q);
	$this->db->or_like('id_users_owner', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Investor_model.php */
/* Location: ./application/models/Investor_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-16 22:44:30 */
/* http://harviacode.com */