<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Menu_masakan_model extends CI_Model
{

    public $table = 'menu_masakan';
    public $id = 'menu_masakan_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('menu_masakan_id,nama_masakan,stok,gambar,harga,full_name as nama_waiter');
        $this->datatables->from('menu_masakan');
        //add this line for join
        //$this->datatables->join('table2', 'menu_masakan.field = table2.field');
        $this->datatables->join('tbl_user', 'tbl_user.id_users = menu_masakan.id_users');
        $this->datatables->add_column('action', anchor(site_url('menu_masakan/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('menu_masakan/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('menu_masakan/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'menu_masakan_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('menu_masakan_id', $q);
	$this->db->or_like('nama_masakan', $q);
	$this->db->or_like('stok', $q);
	$this->db->or_like('gambar', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('id_users', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('menu_masakan_id', $q);
	$this->db->or_like('nama_masakan', $q);
	$this->db->or_like('stok', $q);
	$this->db->or_like('gambar', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('id_users', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Menu_masakan_model.php */
/* Location: ./application/models/Menu_masakan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-17 07:03:22 */
/* http://harviacode.com */