<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pembayaran_pemesanan_model extends CI_Model
{

    public $table = 'pembayaran_pemesanan';
    public $id = 'pembayaran_pemesanan_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('pembayaran_pemesanan_id,tanggal,nominal,pemesanan_masakan_id,nama_pembeli,k.full_name as nama_kasir');
        $this->datatables->from('pembayaran_pemesanan');
        
        //add this line for join
        //$this->datatables->join('table2', 'pembayaran_pemesanan.field = table2.field');
        $this->datatables->join('pemesanan_masakan', 'pembayaran_pemesanan.pemesanan_masakan_id = pemesanan_masakan.pemesanan_maakan_id');
        $this->datatables->join('tbl_user k', 'k.id_users = pembayaran_pemesanan.id_users_kasir');
        $this->datatables->add_column('action', anchor(site_url('pembayaran_pemesanan/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('pembayaran_pemesanan/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('pembayaran_pemesanan/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'pembayaran_pemesanan_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('pembayaran_pemesanan_id', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('nominal', $q);
	$this->db->or_like('pemesanan_masakan_id', $q);
	$this->db->or_like('id_users_kasir', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('pembayaran_pemesanan_id', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('nominal', $q);
	$this->db->or_like('pemesanan_masakan_id', $q);
	$this->db->or_like('id_users_kasir', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pembayaran_pemesanan_model.php */
/* Location: ./application/models/Pembayaran_pemesanan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-21 17:29:04 */
/* http://harviacode.com */