<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Penyusutan_investasi_model extends CI_Model
{

    public $table = 'penyusutan_investasi';
    public $id = 'penusustan_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('penusustan_id,nominal,tanggal,investasi_id');
        $this->datatables->from('penyusutan_investasi');
        //add this line for join
        //$this->datatables->join('table2', 'penyusutan_investasi.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('penyusutan_investasi/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('penyusutan_investasi/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('penyusutan_investasi/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'penusustan_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('penusustan_id', $q);
	$this->db->or_like('nominal', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('investasi_id', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('penusustan_id', $q);
	$this->db->or_like('nominal', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('investasi_id', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Penyusutan_investasi_model.php */
/* Location: ./application/models/Penyusutan_investasi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-15 16:10:53 */
/* http://harviacode.com */