<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Permintaan_peralatan_model extends CI_Model
{

    public $table = 'pengiriman_peralatan';
    public $id = 'pengiriman_peralatan_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('pengiriman_peralatan_id,tanggal,jumlah,nama_peralatan,l.full_name as nama_logistik,a.full_name as nama_adminresto,status');
        $this->datatables->from('pengiriman_peralatan');
        //add this line for join
        //$this->datatables->join('table2', 'pengiriman_peralatan.field = table2.field');
        $this->datatables->join('tbl_user l', 'l.id_users = pengiriman_peralatan.id_users_logistik');
        $this->datatables->join('tbl_user a', 'a.id_users = pengiriman_peralatan.id_users_adminresto');
        $this->datatables->join('peralatan', 'peralatan.peralatan_id = pengiriman_peralatan.peralatan_id');
        $this->datatables->add_column('action', anchor(site_url('permintaan_peralatan/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('permintaan_peralatan/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('permintaan_peralatan/status_dikirim/$1'),'<i class="fa  fa-check" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm'))." 
            ".anchor(site_url('permintaan_peralatan/status_belum_dikirim/$1'),'<i class="fa fa-close" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm'))."    
            ".anchor(site_url('permintaan_peralatan/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'pengiriman_peralatan_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('pengiriman_peralatan_id', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('peralatan_id', $q);
	$this->db->or_like('id_users_logistik', $q);
	$this->db->or_like('id_users_adminresto', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('pengiriman_peralatan_id', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('peralatan_id', $q);
	$this->db->or_like('id_users_logistik', $q);
	$this->db->or_like('id_users_adminresto', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Permintaan_peralatan_model.php */
/* Location: ./application/models/Permintaan_peralatan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-16 17:14:00 */
/* http://harviacode.com */