<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Resto_model extends CI_Model
{

    public $table = 'resto';
    public $id = 'resto_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('resto_id,nama_resto,alamat_resto,telp_resto,nama_kanwil');
        $this->datatables->from('resto');
        //add this line for join
        $this->datatables->join('kanwil', 'kanwil.kanwil_id = resto.kanwil_id');
        $this->datatables->add_column('action', anchor(site_url('resto/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('resto/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('resto/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'resto_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('resto_id', $q);
	$this->db->or_like('nama_resto', $q);
	$this->db->or_like('alamat_resto', $q);
	$this->db->or_like('telp_resto', $q);
	$this->db->or_like('kanwil_id', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('resto_id', $q);
	$this->db->or_like('nama_resto', $q);
	$this->db->or_like('alamat_resto', $q);
	$this->db->or_like('telp_resto', $q);
	$this->db->or_like('kanwil_id', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Resto_model.php */
/* Location: ./application/models/Resto_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-09-25 10:03:47 */
/* http://harviacode.com */