<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Setoran_ke_bendahara_model extends CI_Model
{

    public $table = 'setoran_kasir';
    public $id = 'setoran_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('setoran_id,nominal,tanggal,b.full_name as nama_bendahara,k.full_name as nama_kasir,status');
        $this->datatables->from('setoran_kasir'); 
        //add this line for join
        //$this->datatables->join('table2', 'setoran_kasir.field = table2.field');
        $this->datatables->join('tbl_user b', 'b.id_users = setoran_kasir.id_users_bendahara');
        $this->datatables->join('tbl_user k', 'k.id_users = setoran_kasir.id_users_kasir');
        $this->datatables->add_column('action', anchor(site_url('setoran_ke_bendahara/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('setoran_ke_bendahara/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('setoran_ke_bendahara/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'setoran_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('setoran_id', $q);
	$this->db->or_like('nominal', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('id_users_bendahara', $q);
	$this->db->or_like('id_users_kasir', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('setoran_id', $q);
	$this->db->or_like('nominal', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('id_users_bendahara', $q);
	$this->db->or_like('id_users_kasir', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Setoran_ke_bendahara_model.php */
/* Location: ./application/models/Setoran_ke_bendahara_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-21 17:54:06 */
/* http://harviacode.com */